
public class Rootobject
{
    public int Material_ID { get; set; }
    public string ULVAC { get; set; }
    public string LOT_NUMBER { get; set; }
    public string WAFER_NUMBER { get; set; }
    public string PRODUCT { get; set; }
    public string COLOR { get; set; }
    public string OWNER { get; set; }
    public string TSMC { get; set; }
    public string STACK { get; set; }
    public string ANODE { get; set; }
    public string DATE_RELEASED { get; set; }
    public string EA_NUMBER { get; set; }
    public string LID_TYPE { get; set; }
    public int ID1 { get; set; }
    public int ID { get; set; }
    public float MIN_LUM { get; set; }
    public string PRODUCT_TYPE { get; set; }
    public float DARK_CUR { get; set; }
    public float LUM_LSL { get; set; }
    public int DIMCTL { get; set; }
    public int VGMAX { get; set; }
    public float LUM_TYP { get; set; }
    public float LUM_USL { get; set; }
    public float BRIGHT_CIE_X_LSL { get; set; }
    public int IDRF_LSL { get; set; }
    public int IDRF_USL { get; set; }
    public float BRIGHT_CIE_X_USL { get; set; }
    public float BRIGHT_CIE_Y_LSL { get; set; }
    public float BRIGHT_CIE_Y_USL { get; set; }
    public float RED_CIE_X_LSL { get; set; }
    public float RED_CIE_X_USL { get; set; }
    public float GREEN_CIE_X_LSL { get; set; }
    public float RED_CIE_Y_LSL { get; set; }
    public float RED_CIE_Y_USL { get; set; }
    public float GREEN_CIE_X_USL { get; set; }
    public float BLUE_CIE_X_LSL { get; set; }
    public float GREEN_CIE_Y_LSL { get; set; }
    public float GREEN_CIE_Y_USL { get; set; }
    public float BLUE_CIE_X_USL { get; set; }
    public float BLUE_CIE_Y_LSL { get; set; }
    public float BLUE_CIE_Y_USL { get; set; }
    public float SLOPE_LSL { get; set; }
    public float SLOPE_USL { get; set; }
    public float ORIG1_LSL { get; set; }
    public float ORIG1_USL { get; set; }
    public float VGN0_LSL { get; set; }
    public float VGN0_USL { get; set; }
    public float VGN1_LSL { get; set; }
    public float VGN1_USL { get; set; }
    public float VGN2_LSL { get; set; }
    public float VGN2_USL { get; set; }
    public float VGN3_LSL { get; set; }
    public float VGN3_USL { get; set; }
    public float VGN4_LSL { get; set; }
    public float VGN4_USL { get; set; }
    public float VGN5_LSL { get; set; }
    public float VGN5_USL { get; set; }
    public float VGN6_LSL { get; set; }
    public float VGN6_USL { get; set; }
    public float VGN7_LSL { get; set; }
    public float VGN7_USL { get; set; }
    public float LAU_LSL { get; set; }
    public float LOW_VGN0_LSL { get; set; }
    public float LOW_VGN0_USL { get; set; }
    public float LOW_VGN1_LSL { get; set; }
    public float LOW_VGN1_USL { get; set; }
    public float LOW_VGN2_LSL { get; set; }
    public float LOW_VGN2_USL { get; set; }
    public float LOW_VGN3_LSL { get; set; }
    public float LOW_VGN3_USL { get; set; }
    public float LOW_VGN4_LSL { get; set; }
    public float LOW_VGN4_USL { get; set; }
    public float LOW_VGN5_LSL { get; set; }
    public float LOW_VGN5_USL { get; set; }
    public float LOW_VGN6_LSL { get; set; }
    public float LOW_VGN6_USL { get; set; }
    public float LOW_VGN7_LSL { get; set; }
    public float LOW_VGN7_USL { get; set; }
    public float DISPOFF_5V_I_LSL { get; set; }
    public float DISPOFF_5V_I_USL { get; set; }
    public float DISPOFF_2V5_I_LSL { get; set; }
    public float DISPOFF_2V5_I_USL { get; set; }
    public float DISPOFF_1V8_I_LSL { get; set; }
    public float DISPOFF_1V8_I_USL { get; set; }
    public float GL0_5V_I_LSL { get; set; }
    public float GL0_5V_I_USL { get; set; }
    public float GL0_4V_I_LSL { get; set; }
    public float GL0_4V_I_USL { get; set; }
    public float GL0_3V3_I_LSL { get; set; }
    public float GL0_3V3_I_USL { get; set; }
    public float GL0_2V5_I_LSL { get; set; }
    public float GL0_2V5_I_USL { get; set; }
    public float GL0_1V8_I_LSL { get; set; }
    public float GL0_1V8_I_USL { get; set; }
    public float GL0_VCOM_I_LSL { get; set; }
    public float GL0_VCOM_I_USL { get; set; }
    public float GL255_5V_I_LSL { get; set; }
    public float GL255_5V_I_USL { get; set; }
    public float GL255_4V_I_LSL { get; set; }
    public float GL255_4V_I_USL { get; set; }
    public float GL255_3V3_I_LSL { get; set; }
    public float GL255_3V3_I_USL { get; set; }
    public float GL255_2V5_I_LSL { get; set; }
    public float GL255_2V5_I_USL { get; set; }
    public float GL255_1V8_I_LSL { get; set; }
    public float GL255_1V8_I_USL { get; set; }
    public float GL255_VCOM_I_LSL { get; set; }
    public float GL255_VCOM_I_USL { get; set; }
}
